#
#	General Makefile for the 3D ADI Advec-diff problem
#
#

all:	

	$(MAKE) $(MFLAGS) -C ./thrd11 all
	$(MAKE) $(MFLAGS) -C ./thrd12 all
	$(MAKE) $(MFLAGS) -C ./thrd13 all
	$(MAKE) $(MFLAGS) -C ./thrd14 all
clean:

	$(MAKE) -C ./thrd11 clean
	$(MAKE) -C ./thrd12 clean
	$(MAKE) -C ./thrd13 clean
	$(MAKE) -C ./thrd14 clean

### DO NOT remove this line - make depends on it ### 